### ISSUE TITLE
Translate procedure inefficiency problem

### ISSUE THREAD

**Issue by wjbianjason** [soskek/convolutional_seq2seq#1]
Thanks for your work to implement the paper, which did me a big favor.
When I apply translate procedure, I find there is no beam search and re-run decoded word again and again in in every decode time-step.
```python
    for i in range(max_length):
        log_prob_tail = self(x_block, y_block, y_block,
                             get_prediction=True)
        ys = self.xp.argmax(log_prob_tail.data, axis=1).astype('i')
        result.append(ys)
        y_block = F.concat([y_block, ys[:, None]], axis=1).data         
```
As we can see, encode model is executed again and again, the same as decoded word.
Do you have a plan to improve this?

**Comment by soskek** [comment]
Thank you for reading and using my code!
Yes. As you say and [my comment](https://github.com/soskek/convolutional_seq2seq/blob/d9012db0754d10baa13761bf5f4c85dd05728a78/net.py#L269), this currently does not support beam search and efficient decoding. This is just because of economy of (my) time.
Both of them can be fixed and extended (like [this](https://github.com/chainer/chainer/pull/2344)) if I try. But, I have no plan for the moment.
