### ISSUE TITLE
how to test?

### ISSUE THREAD

**Issue by mengya22** [soskek/convolutional_seq2seq#2]
i am new in chainer . In this project, i can train but i do not know how to test

**Comment by soskek** [comment]
Thank you for running my code (and using Chainer!!). Do you mean that "test" is observing generated sentences? This repository has no inference-specific script, but the training script performs translation generation and shows the result (generated sentences and BLEU score) regularly during training. You can see them first after some iterations (maybe 200).
Otherwise, if extracting [this method](https://github.com/soskek/convolutional_seq2seq/blob/master/seq2seq.py#L240-L248), you can make a script for loading a trained model and exploiting it.
